### ISSUE TITLE
[FEAT] Integrate the DataProcessor object into current regular synthesizers process.

### ISSUE THREAD

**Issue by fabclmnt** [ydataai/ydata-synthetic#118]
## Description
To remove the friction of using new datasets with the current architectures, we are offering a new object DataProcessor that will perform basic preprocessing on the provided data. This preprocessing will run at the training step. 

## Tasks:
- Validate the feasibility of integrating the DataProcessor into the BaseSynthesizer
- Integrate DataProcessor in the current training flow. 
- Set an input parameter for the :meth: train with the datatypes.
- Set an input parameter for the :meth: train - processing - if set to 'True' the data needs to be processed, otherwise is assumed that the user already processed the data.

**Comment by jfsantos-ds** [comment]
2 expected modes of synthesizer training:
- with processing (default mode): `synthesizer.train(data=data, train_args=train_args, processor=processor, col_types=col_types, pre_processed=False) `
- without processing or with _a priori_ user processing: `synthesizer.train(data=preprocessed_data, train_args=train_args, processor=None, col_types=None, pre_processed=True)`
