### ISSUE TITLE
Packaging and Release automation for PyPi: ydata-synthetic

### ISSUE THREAD

**Issue by gmartinsribeiro** [ydataai/ydata-synthetic#12]
Create build pipelines for the ydata-synthetic lib to be published on PyPi

**Comment by akanz1** [comment]
Great project you put together here! I havent had a chance to look at the models in detail but it looks very interesting and i'll surely give data synthetisation a try!

Regarding this issue: Is it still open and relevant?

If so, what are you imagining? Would it be sufficient to establish a Github Action that builds and pushes the package to PyPi?

The following .yaml sets up a Github actions workflow and is triggered each time you push a tag on a commit starting with "v", as in "v0.3.1" or similar. All it takes is a PyPi account with the credentials stored in your Github Secrets.

https://github.com/akanz1/klib/blob/main/.github/workflows/pythonpublish.yml

Let me know if that's something for you / feel free to use or adjust the workflow and reach out in case you have any questions! :)
