### ISSUE TITLE
[Question] WGAN-GP for timeseries data

### ISSUE THREAD

**Issue by pbezz1** [ydataai/ydata-synthetic#137]
Can I use WGAN-GP for timeseries data such as stock data? If yes do I need to preprocess the data to create sequences of say 24 data points in the same way described for the TimeGAN approach?
Any help or direction is much appreciated. Thanks.

**Comment by jfsantos-ds** [comment]
Hey Patrick!
For this you would need either an RNN synthesizer ran in a stateful manner or a conditional generator. WGAN_GP does not meet any of these! See this synthesizer as a [vanilla GAN](https://arxiv.org/abs/1406.2661) with [Wasserstein loss](https://arxiv.org/abs/1701.07875) and [Gradient Penalty](https://arxiv.org/abs/1704.00028) instead. (Not indicated for time series)
