### ISSUE TITLE
[BUG] 'gumbel_softmax_activation_5/******/' is not a valid scope name

### ISSUE THREAD

**Issue by INSACY98** [ydataai/ydata-synthetic#143]
**Describe the bug**
`ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/ydata_synthetic/utils/gumbel_softmax.py:77 call  *
        cat_cols = [GumbelSoftmaxLayer(name=name)(col)[0] for name, col in             zip(self.cat_feats.feat_names_in, cat_cols)]
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:1006 __call__  **
        with ops.name_scope_v2(name_scope):
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:6650 __enter__
        scope_name = scope.__enter__()
    /usr/lib/python3.7/contextlib.py:112 __enter__
        return next(self.gen)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:4241 name_scope
        raise ValueError("'%s' is not a valid scope name" % name)

    ValueError: 'gumbel_softmax_activation_5/*********/' is not a valid scope name`

******* is the cat_cols that we are using in our dataset
We can only use num_cols by specifying cat_cols=[]. Any cat_cols with values will cause this error.

**Expected behavior**
How to run VanillaGan and WGAN_GP with categorical features included.
Currently, we followed the example in https://github.com/ydataai/ydata-synthetic/blob/dev/examples/regular/adult_wgangp.py

**Desktop (please complete the following information):**
We are working in google colab.

**Comment by jfsantos-ds** [comment]
Hello @INSACY98! Can you please provide information on the system and the versions of ydata_synthetic and tensorflow libraries in the environment that you are using? Thanks in advance

**Comment by INSACY98** [comment]
Hi @jfsantos-ds! We are using google colab for coding and the version of the two packages are ydata_synthetic-0.6.1 and TensorFlow-2.4.4. Thanks.

**Comment by fabclmnt** [comment]
@INSACY98 the GumbelSoftmax implementation has been deactivated. 

We will have it activated again, but in the meantime, you will be able to run any architecture while specifying categorical and continuous.
