### ISSUE TITLE
TimeGAN - Synthetic stock data.ipynb: cannot import name 'ModelParameters'

### ISSUE THREAD

**Issue by aloksmenthe** [ydataai/ydata-synthetic#149]
Hello,
While executing the imports for the example notebook following error is received

from ydata_synthetic.synthesizers import ModelParameters
Traceback (most recent call last):
  File "C:\Users\xxxxx\Anaconda3\envs\xxxx\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-12c9bc17a982>", line 1, in <module>
    from ydata_synthetic.synthesizers import ModelParameters
ImportError: cannot import name 'ModelParameters'

**Versions** used :
ydata-synthetic-0.2.0
tensorflow-2.3.4

Thanks,
Alok

**Comment by fahim-sikder** [comment]
Hi,

Try with python `version 3.8` with Anaconda, I was also having the same problem updating the python version works for me!
