### ISSUE TITLE
Convert synthetic data to useful dataset

### ISSUE THREAD

**Issue by PabDJ** [ydataai/ydata-synthetic#169]
In the example that can be found in Time Series folder we can observed how the data set from the CSV file is transformed to a 3-D numpy array. After that, the GAN generates a synthetic array with shape (3712, 24, 6).
How can I transform this data into a shape that looks as the original CSV file? I mean, at first we got 3685 rows and 6 columns, how can I achieve this shape for the generated data? Is there any possible transformation so that the synthetic data can be used as typical dataframe for future experiments?
Regards

**Comment by fabclmnt** [comment]
Hi @PabDJ,

given TimeGAN architecture, that is not possible. The architecture is designed to learn and replicate time-windows. This is highly useful for window-based time-series classification.

For what you're aiming, I would recommend to go for a different architecture.
