### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oky4nd4y** [ydataai/ydata-synthetic#219]
**Describe the bug**

**To Reproduce**
1. Go to '[...](https://github.com/ydataai/ydata-synthetic/blob/dev/examples/regular/models/adult_wgangp.py)'
2. Click on '
pip install pmlb
pip install ydata-synthetic'
4. Scroll down to '
from pmlb import fetch_data

from ydata_synthetic.synthesizers.regular import WGAN_GP
from ydata_synthetic.synthesizers import ModelParameters, TrainParameters

model = WGAN_GP'
5. See error

**Error**
ImportError                               Traceback (most recent call last)
[<ipython-input-3-337f57259ee7>](https://localhost:8080/#) in <module>
      1 from pmlb import fetch_data
      2 
----> 3 from ydata_synthetic.synthesizers.regular import WGAN_GP
      4 from ydata_synthetic.synthesizers import ModelParameters, TrainParameters
      5 

ImportError: cannot import name 'WGAN_GP' from 'ydata_synthetic.synthesizers.regular' (/usr/local/lib/python3.8/dist-packages/ydata_synthetic/synthesizers/regular/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Screenshots**

**Desktop (please complete the following information):**
 - Google Colab

**Additional context**

**Comment by isacmoura** [comment]
I had the same problem and a workaround to use WGANGP while the team don't fix this bug is setting the version to 0.7.0.

You can install it by pip:
`pip install ydata-synthetic==0.7.0`

**Comment by aquemy** [comment]
Hi,

It should be solved since `0.9.0`. The examples have been fixed (the import is now slightly different).
Please, re-open if you have any issue.
