### ISSUE TITLE
[BUG] Python 3.8 error 

### ISSUE THREAD

**Issue by 9jaswag** [ydataai/ydata-synthetic#243]
**Describe the bug**
Unable to import `RegularSynthesizer`

**To Reproduce**
Steps to reproduce the behaviour:
1. In Google Colab, install ydata-synthetic: `!pip install ydata-synthetic`
2. Import `RegularSynthesizer`: `from ydata_synthetic.synthesizers.regular import RegularSynthesizer`
3. See error: `TypeError: 'type' object is not subscriptable`

**Expected behaviour**
I expect

**Screenshots**
![Screenshot 2023-03-05 at 4 06 29 PM](https://user-images.githubusercontent.com/8125356/222968630-364dfd8a-dd85-4515-8271-c7f0a3b65f83.png)

**Desktop (please complete the following information):**
- Google Colab running Python 3.8.10

**Comment by fabclmnt** [comment]
Hi @9jaswag ,

the code no longer support python3.8. You can overcome this challenge by upgrading your Colab to python 3.9. 

I'll be happy to assist you with the python upgrade in case that is feasible.

**Comment by 9jaswag** [comment]
> Hi @9jaswag ,
> 
> the code no longer support python3.8. You can overcome this challenge by upgrading your Colab to python 3.9.
> 
> I'll be happy to assist you with the python upgrade in case that is feasible.

Hi @fabclmnt, thanks for the response. I'll try upgrading Colab to Python 3.9 and share an update here.

**Comment by 9jaswag** [comment]
Works now! Thanks for your help @fabclmnt 🙏
