### ISSUE TITLE
[FEAT] Landing page

### ISSUE THREAD

**Issue by gmartinsribeiro** [ydataai/ydata-synthetic#26]
**Describe the solution you'd like**
Landing page for the [syntheticdata.community](url)

Two call to action:
1. Join our slack: slack.ydata.ai
2. Check out our GitHub: https://github.com/ydataai/ydata-synthetic

The footer (or a section below) should mention that YData is the company behind the community

**Describe alternatives you've considered**
Alternative 1: Use materials/design/etc from YData website
Alternative 2: Use other template

**Additional context**
Logos in attachment
[Synthetic data.zip](https://github.com/ydataai/ydata-synthetic/files/5837184/Synthetic.data.zip)

**Comment by portellaa** [comment]
it's allliiiveeee 🚀
