### ISSUE TITLE
[BUG] ydata fails to import on fresh Docker container

### ISSUE THREAD

**Issue by DGaffney** [ydataai/ydata-synthetic#304]
**Describe the bug**
For some reason, when trying to load this package in a fresh Docker container, a protobuf error is thrown:
```
>>> from ydata_synthetic.synthesizers.regular import RegularSynthesizer
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:560] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```
[example.zip](https://github.com/ydataai/ydata-synthetic/files/12602300/example.zip)

**To Reproduce**
unzip and build attached Docker container

**Expected behavior**
This should load the Regular Synthesizer

**Comment by fabclmnt** [comment]
Hi @DGaffney, 

this seems to be a known issue on TFX side. Have you had a look into this github discussion: https://github.com/tensorflow/tfx/issues/5935

**Comment by DGaffney** [comment]
@fabclmnt thanks for that! I'll close for now, much appreciated.
