### ISSUE TITLE
Doppelganger Training Parameters

### ISSUE THREAD

**Issue by iamamiramine** [ydataai/ydata-synthetic#340]
I am trying to run doppelganger from **examples/timeseries/mba_doppelganger.py**. Could you please explain what are the parameters that I need to run the model and what they each correspond to? I do understand most of the parameters, but I am a bit confused about what `measurement_cols` is. When I use a specific column as `measurement_col` and try to generate a new sample, the values for this `measurement_col` are always off.

**Comment by Mr-Teal** [comment]
Same problem here. I do not know the meaning for most of the parameters in TrainParameters and ModelParameters and hence do not know whether I need to set them. What's worse is that I found the doc for ydata-synthetic did not include anything about the TrainParameters and ModelParameters.

**Comment by iamamiramine** [comment]
measurement_cols are the continuous variables in the dataset
