### ISSUE TITLE
[BUG] Slack link not working

### ISSUE THREAD

**Issue by crownpku** [ydataai/ydata-synthetic#39]
"Invitation expired
It looks like you’re trying to accept an invitation, but the link was deactivated."

**Comment by andre-lx** [comment]
The link is working from the slack.ydata.ai URL.

Can you share some screenshot please? You are trying to access from which URL? 

Because the URL from slack will expire in 5 days, and before that I can't create a new one.

**Comment by crownpku** [comment]
Somehow it works now... closing the issue.
