### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DavidJardim** [ydataai/ydata-synthetic#40]
This error occurs when I try to install ydata-synthetic lib, any idea if i'm doing something wrong?
![image](https://user-images.githubusercontent.com/940815/107549166-65789f80-6bc7-11eb-9eb3-17c1e3066729.png)

**Comment by fabclmnt** [comment]
Use` !pip install ydata-synthetic` instead.

(https://pypi.org/project/ydata-synthetic/)

**Comment by DavidJardim** [comment]
Thank you!

**Comment by moonastar** [comment]
This error is “ModuleNotFoundError: No module named 'ydata_synthetic.preprocessing.regular.credit_fraud'，it is the version error？

**Comment by JazOjeda** [comment]
I also have this error
 No module named 'ydata_synthetic.preprocessing.regular.credit_fraud'
Could you solve it?
