### ISSUE TITLE
Where is the function processed_stock?

### ISSUE THREAD

**Issue by MritulaC** [ydataai/ydata-synthetic#54]
While running the below code inn The data section of TimeGAN - Synthetic stock data.ipynb file, I am getting error:
stock_data = processed_stock(seq_len=seq_len)
print(len(stock_data),stock_data[0].shape)

Error:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/ydata_synthetic/preprocessing/data/stock.csv'

**Comment by fabclmnt** [comment]
The .csv file is in the directory where you've installed the package. 

There's a need to change the path from where the file is being loaded.  In the meantime, you can use the dataset and apply your own preprocessing. Or run the following code locally. 

`stock_url = 'https://query1.finance.yahoo.com/v7/finance/download/GOOG?period1=1483228800&period2=1611446400&interval=1d&events=history&includeAdjustedClose=true'
        request = req.get(stock_url)
        url_content = request.content

        file_path = os.path.join(os.path.dirname(os.path.join('..', os.path.dirname(__file__))), 'data')
        stock_csv = open(os.path.join(file_path, 'stock.csv'), 'wb')
        stock_csv.write(url_content)
        # Reading the stock data
        stock_df = pd.read_csv('../data/stock.csv')

    try:
        stock_df = stock_df.set_index('Date').sort_index()
    except:
        stock_df=stock_df
    #Data transformations to be applied prior to be used with the synthesizer model
    processed_data = real_data_loading(stock_df.values, seq_len=seq_len)`

Sorry for the inconvenience.
