### ISSUE TITLE
[BUG] Error with tensorflow using WGANGP

### ISSUE THREAD

**Issue by mikel-hernandezj** [ydataai/ydata-synthetic#63]
Hi!

I am trying to use WGANGP from your GitHub repository and I have the following error: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'.

The days before I was able to use this model without any problem, but today it gives me this error. I don't know how I can fix it.

Thank you,
Mikel

**Comment by fabclmnt** [comment]
Hi Mikel, 
no change was done in the package in between. The suspicion is that is related to the version of Tensorflow you've on your virtual env. 
I'll be closing the issue, let's keep the conversation in the slack until there's further details.
