### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sorooshi** [ydataai/ydata-synthetic#68]
First of all, thank you for the work.

**Describe the bug**
I am trying to train a TimeGAN on my own dataset. 
I used the preprocessing function, i.e, real_data_loading() func, from preprocessing.utils to prepare the data. 
And all my parameter settings are the same as what you explained in the [this](https://colab.research.google.com/github/ydataai/ydata-synthetic/blob/master/examples/timeseries/TimeGAN_Synthetic_stock_data.ipynb#scrollTo=uYCF_8JT_t_j) jupyter notebook, except for changing the number of sequences which is equal to the number of the columns of my dataset.

**To Reproduce**
1. Go to 'https://github.com/Sorooshi/SuperOX'
2. Click on 'u06-TGAN.ipynb'
3. Scroll down to 'cell [19]'

**Expected behavior**
The expected dimension should be (69, 1, 10) where 69 is batch_size.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.
 

**Additional context**

**Comment by fabclmnt** [comment]
Hi @Sorooshi this is not a bug. 

As you can see per the error returned, the GAN architecture is expecting an object with the following structure: (batch_size, 24, 10).

`ValueError: Input 0 is incompatible with layer model: expected shape=(None, 24, 10), found shape=(69, 1, 10)`

You're passing an object with the structure (69,1,10). The processing provided is not generalizable, meaning it was build for the example dataset. It's expected that the preprocessing is adapted to adapt the new data into the structure expected by the network. 

In the future we will provide more generalizable processing methods. For the moment we only ensure that the example dataset will work.

**Comment by Sorooshi** [comment]
@fabclmnt Correct me if I'm mistaken: this error arises not because of the preprocessing but because of the TGAN code, that is when you train the autoencoder!

It has nothing to do with preprocessing

**Comment by fabclmnt** [comment]
The error is still due to the preprocessing - meaning the architecture is expecting a structure on the vector side if you are providing a structure that is not compatible with what we are expecting at the TGAN level, the problem is from the preprocessing. 

The  architecture was developed under certain assumptions.
