### ISSUE TITLE
evaluate result

### ISSUE THREAD

**Issue by zhixiongtan** [ydataai/ydata-synthetic#70]
Thanks for your wonderful work!

I have a question. How can I evaluate my result in this repo.

Thanks again!

**Comment by fabclmnt** [comment]
Hi @zhixiongtan thank you for your question. 

We are working on having that available in the repo in the next release.

**Comment by zhixiongtan** [comment]
@fabclmnt hello!
sooo thanks for your reply in github about evaluate question. is there any materials that I can learn about evaluate before you release your new repro?

**Comment by zhixiongtan** [comment]
thanks for your reply!
