### ISSUE TITLE
 [BUG] AttributeError: 'TimeGAN' object has no attribute '__MODEL__'

### ISSUE THREAD

**Issue by RodrigoAbrao** [ydataai/ydata-synthetic#83]
If you execute this notebook https://github.com/ydataai/ydata-synthetic/blob/master/examples/timeseries/TimeGAN_Synthetic_stock_data.ipynb

At the line synth.save() you'll get this:
AttributeError: 'TimeGAN' object has no attribute '__MODEL__'

**Comment by fabclmnt** [comment]
Witht the new release the solution already implemented will be available.

**Comment by Nasrin15** [comment]
@fabclmnt  I am afraid it still doesnot solve the error it shows same error 'ImportError: cannot import name 'ModelParameters' from 'ydata_synthetic.synthesizers'
