### ISSUE TITLE
[FEAT] Add CGAN for Time-Series

### ISSUE THREAD

**Issue by jfsantos-ds** [ydataai/ydata-synthetic#93]
Time-series is one of the major points of research for data synthesis. The amount of research and offered open repos is low, so a key differentiator is the availability of such architecture for time-series. 

**Requirements**: TF 2 implementation

**Article**: https://www.naun.org/main/NAUN/neural/2020/a082016-004(2020).pdf

**Repository**: https://github.com/ydataai/ydata-synthetic/

**Priority**: Medium

**Effort**: Medium

**Comment by Nasrin15** [comment]
Hey @jfsantos-ds ,
Can you please explain this feature there are no comments. Is there CGAN for time series data I couldnot find one?

**Comment by fabclmnt** [comment]
@Nasrin15 is not merged hence you cannot find it. 

It will be made available in the next big release of the package.
